### ISSUE TITLE
logback.xml missing in JPACKAGE.

### ISSUE THREAD

**Issue by ghost** [beryx-gist/badass-runtime-example#2]
How to copy the files to jpackage?

**Comment by siordache** [comment]
https://github.com/beryx-gist/badass-runtime-example/blob/01908dda7cd94c178fc727547cf50ca8ef069bae/build.gradle#L43-L48

**Comment by ghost** [comment]
@siordache this code not worked.

**Comment by siordache** [comment]
See https://github.com/beryx-gist/badass-runtime-example/issues/1#issuecomment-912947566

**Comment by ghost** [comment]
@siordache I tried but file missing in jpackage.

**Comment by siordache** [comment]
There was still a problem:
https://github.com/beryx-gist/badass-runtime-example/issues/1#issuecomment-913019118

**Comment by ghost** [comment]
@siordache I tried but same issue

**Comment by siordache** [comment]
Duplicate of #1
