### ISSUE TITLE
How to copy logback.xml into {{BIN_DIR}}  this folder ?

### ISSUE THREAD

**Issue by ghost** [beryx-gist/badass-runtime-example#4]
I want to paste logback.xml file into {{BIN_DIR}} folder 📂. 

    jvmArgs = [ '-Dlog4j.configurationFile={{BIN_DIR}}/log4j2.xml' ]

How can I do this?

**Comment by siordache** [comment]
Try this:
```
tasks.jpackage.doFirst {
    def currentOs = org.gradle.internal.os.OperatingSystem.current()
    def binPath = currentOs.windows ? project.name : currentOs.linux ? "$project.name/bin" : "${project.name}.app/Contents/MacOS"    
    copy {
        from('src/main/resources')
        into("$buildDir/jpackage/$binPath")
    }
}
```

**Comment by poorvajappja** [comment]
def binPath = currentOs.windows ? project.name : currentOs.linux ? "$project.name/bin" : "${project.name}.app/Contents/MacOS" 

Why you didn't add  this code  `"${project.name}.app/Contents/MacOS"` in build.gradle file ?
